services:
  - type: web
    name: laserstrike-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
    region: ohio
